# Generated by Django 4.1.4 on 2023-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioEmpleadores',
            fields=[
                ('id_cuestionario', models.AutoField(db_column='ID_CUESTIONARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('pregunta_4', models.PositiveIntegerField(blank=True, db_column='PREGUNTA_4', null=True)),
                ('pregunta_5', models.CharField(blank=True, db_column='PREGUNTA_5', max_length=1000, null=True)),
                ('pregunta_6', models.PositiveIntegerField(blank=True, db_column='PREGUNTA_6', null=True)),
                ('pregunta_38', models.IntegerField(blank=True, db_column='PREGUNTA_38', null=True)),
                ('pregunta_39', models.IntegerField(blank=True, db_column='PREGUNTA_39', null=True)),
                ('pregunta_40', models.IntegerField(blank=True, db_column='PREGUNTA_40', null=True)),
                ('pregunta_41', models.IntegerField(blank=True, db_column='PREGUNTA_41', null=True)),
                ('pregunta_42', models.IntegerField(blank=True, db_column='PREGUNTA_42', null=True)),
                ('pregunta_43', models.IntegerField(blank=True, db_column='PREGUNTA_43', null=True)),
                ('pregunta_44', models.IntegerField(blank=True, db_column='PREGUNTA_44', null=True)),
                ('pregunta_45', models.IntegerField(blank=True, db_column='PREGUNTA_45', null=True)),
                ('pregunta_46', models.IntegerField(blank=True, db_column='PREGUNTA_46', null=True)),
                ('pregunta_47', models.IntegerField(blank=True, db_column='PREGUNTA_47', null=True)),
                ('pregunta_60', models.PositiveIntegerField(db_column='PREGUNTA_60')),
                ('pregunta_61', models.PositiveIntegerField(db_column='PREGUNTA_61')),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta10',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta11',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta12',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta13',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_13',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta14',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_14',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta15',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_15',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta16',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta17',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta18',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta19',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_19',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta2',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta20',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta21',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta22',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta23',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_23',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta24',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_24',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta25',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_25',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta26',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_26',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta27',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_27',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta28',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_28',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta29',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_29',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta3',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta30',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta31',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_31',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta32',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_32',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta33',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_33',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta34',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_34',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta35',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_35',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta36',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_36',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta37',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_37',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta48',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_48',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta49',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_49',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta50',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_50',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta51',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_51',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta52',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_52',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta53',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_53',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta54',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_54',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta55',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_55',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta56',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_56',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta57',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_57',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta58',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_58',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta59',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_59',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta62',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_62',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta63',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_63',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta64',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_64',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta7',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta8',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioEmpleadoresPregunta9',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_EMPLEADORES_PREGUNTA_9',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=50)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta10',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta11',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta12',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta15',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_15',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta16',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta17',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta18',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta19',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_19',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta2',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta20',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta21',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta22',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta23',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_23',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta24',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_24',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta25',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_25',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta26',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_26',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta27',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_27',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta28',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_28',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta29',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_29',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta3',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta30',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta31',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_31',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta32',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_32',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta33',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_33',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta34',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_34',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta35',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_35',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta36',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_36',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta37',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_37',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta38',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_38',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta39',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_39',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta4',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta5',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta6',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta7',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta8',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransevrsalPregunta9',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=300)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSEVRSAL_PREGUNTA_9',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTransversal',
            fields=[
                ('id_cuestionario', models.AutoField(db_column='ID_CUESTIONARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('pregunta_13', models.CharField(db_column='PREGUNTA_13', max_length=500)),
                ('pregunta_14', models.CharField(db_column='PREGUNTA_14', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSVERSAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoria',
            fields=[
                ('id_cuestionario', models.AutoField(db_column='ID_CUESTIONARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('pregunta_4', models.CharField(db_column='PREGUNTA_4', max_length=500)),
                ('pregunta_8', models.PositiveIntegerField(db_column='PREGUNTA_8')),
                ('pregunta_40', models.PositiveIntegerField(db_column='PREGUNTA_40')),
                ('pregunta_41', models.PositiveIntegerField(db_column='PREGUNTA_41')),
                ('pregunta_42', models.PositiveIntegerField(db_column='PREGUNTA_42')),
                ('pregunta_43', models.PositiveIntegerField(db_column='PREGUNTA_43')),
                ('pregunta_44', models.PositiveIntegerField(db_column='PREGUNTA_44')),
                ('pregunta_45', models.PositiveIntegerField(db_column='PREGUNTA_45')),
                ('pregunta_46', models.PositiveIntegerField(db_column='PREGUNTA_46')),
                ('pregunta_47', models.PositiveIntegerField(db_column='PREGUNTA_47')),
                ('pregunta_48', models.PositiveIntegerField(db_column='PREGUNTA_48')),
                ('pregunta_49', models.PositiveIntegerField(db_column='PREGUNTA_49')),
                ('pregunta_50', models.PositiveIntegerField(db_column='PREGUNTA_50')),
                ('pregunta_51', models.PositiveIntegerField(db_column='PREGUNTA_51')),
                ('pregunta_52', models.PositiveIntegerField(db_column='PREGUNTA_52')),
                ('pregunta_53', models.PositiveIntegerField(db_column='PREGUNTA_53')),
                ('pregunta_54', models.PositiveIntegerField(db_column='PREGUNTA_54')),
                ('pregunta_55', models.PositiveIntegerField(db_column='PREGUNTA_55')),
                ('pregunta_56', models.PositiveIntegerField(db_column='PREGUNTA_56')),
                ('pregunta_57', models.PositiveIntegerField(db_column='PREGUNTA_57')),
                ('pregunta_58', models.PositiveIntegerField(db_column='PREGUNTA_58')),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta10',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta11',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta12',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta13',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_13',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta14',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_14',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta15',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_15',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta16',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta17',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta18',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta19',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_19',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta2',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta20',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta21',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta22',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta23',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_23',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta24',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_24',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta25',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_25',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta26',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_26',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta27',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_27',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta28',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_28',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta29',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_29',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta3',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta30',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta31',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_31',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta32',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_32',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta33',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_33',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta34',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_34',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta35',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_35',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta36',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_36',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta37',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_37',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta38',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_38',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta39',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_39',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta40',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_40',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta41',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_41',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta42',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_42',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta43',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_43',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta44',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_44',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta45',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_45',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta46',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_46',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta47',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_47',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta48',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_48',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta49',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_49',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta5',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta50',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_50',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta51',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_51',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta52',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_52',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta53',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_53',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta54',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_54',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta55',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_55',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta56',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_56',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta57',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_57',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta58',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_58',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta6',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta7',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta8',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioTrayectoriaPregunta9',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='RESPUESTA', max_length=500)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRAYECTORIA_PREGUNTA_9',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id_pa', models.AutoField(db_column='ID_PA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=600, null=True)),
            ],
            options={
                'db_table': 'PROGRAMA_ACADEMICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id_ua', models.AutoField(db_column='ID_UA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=500, null=True)),
                ('siglas', models.CharField(blank=True, db_column='SIGLAS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'UNIDAD_ACADEMICA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('apellido1', models.CharField(db_column='APELLIDO1', max_length=50)),
                ('apellido2', models.CharField(db_column='APELLIDO2', max_length=50)),
                ('curp', models.CharField(db_column='CURP', max_length=50)),
                ('sexo', models.CharField(blank=True, db_column='SEXO', max_length=30, null=True)),
                ('edad', models.PositiveIntegerField(db_column='EDAD')),
                ('estado_civil', models.CharField(db_column='ESTADO_CIVIL', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50)),
                ('pais', models.CharField(db_column='PAIS', max_length=200)),
                ('codigo_postal', models.CharField(db_column='CODIGO_POSTAL', max_length=10)),
                ('entidad_federativa', models.CharField(db_column='ENTIDAD_FEDERATIVA', max_length=200)),
                ('alcaldia_municipio', models.CharField(db_column='ALCALDIA_MUNICIPIO', max_length=200)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
    ]
