# Generated by Django 4.1.4 on 2023-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_edad_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(db_column='ID_PAIS', primary_key=True, serialize=False)),
                ('pais', models.CharField(db_column='PAIS', max_length=200)),
            ],
            options={
                'db_table': 'PAIS',
                'managed': False,
            },
        ),
    ]
