# Generated by Django 4.1.4 on 2023-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioTransversal',
            fields=[
                ('id_cuestionario_transversal', models.AutoField(db_column='ID_CUESTIONARIO_TRANSVERSAL', primary_key=True, serialize=False)),
                ('pregunta_1', models.CharField(db_column='PREGUNTA_1', max_length=200)),
                ('pregunta_2', models.CharField(blank=True, db_column='PREGUNTA_2', max_length=200, null=True)),
                ('pregunta_3', models.CharField(db_column='PREGUNTA_3', max_length=200)),
                ('pregunta_4', models.CharField(db_column='PREGUNTA_4', max_length=200)),
                ('pregunta_5', models.CharField(blank=True, db_column='PREGUNTA_5', max_length=200, null=True)),
                ('pregunta_6', models.CharField(db_column='PREGUNTA_6', max_length=200)),
                ('pregunta_7', models.CharField(db_column='PREGUNTA_7', max_length=200)),
                ('pregunta_8', models.CharField(db_column='PREGUNTA_8', max_length=200)),
                ('pregunta_9', models.CharField(db_column='PREGUNTA_9', max_length=200)),
                ('pregunta_10', models.CharField(blank=True, db_column='PREGUNTA_10', max_length=200, null=True)),
                ('pregunta_11', models.CharField(blank=True, db_column='PREGUNTA_11', max_length=200, null=True)),
                ('pregunta_12', models.CharField(blank=True, db_column='PREGUNTA_12', max_length=200, null=True)),
                ('pregunta_13', models.CharField(db_column='PREGUNTA_13', max_length=200)),
                ('pregunta_14', models.CharField(db_column='PREGUNTA_14', max_length=200)),
                ('pregunta_15', models.CharField(db_column='PREGUNTA_15', max_length=200)),
                ('pregunta_16', models.CharField(db_column='PREGUNTA_16', max_length=200)),
                ('pregunta_17', models.CharField(blank=True, db_column='PREGUNTA_17', max_length=200, null=True)),
                ('pregunta_18', models.CharField(blank=True, db_column='PREGUNTA_18', max_length=200, null=True)),
                ('pregunta_19', models.CharField(db_column='PREGUNTA_19', max_length=200)),
                ('pregunta_20', models.CharField(db_column='PREGUNTA_20', max_length=200)),
                ('pregunta_21', models.CharField(db_column='PREGUNTA_21', max_length=200)),
                ('pregunta_22', models.CharField(blank=True, db_column='PREGUNTA_22', max_length=200, null=True)),
                ('pregunta_23', models.CharField(blank=True, db_column='PREGUNTA_23', max_length=200, null=True)),
                ('pregunta_24', models.CharField(blank=True, db_column='PREGUNTA_24', max_length=200, null=True)),
                ('pregunta_25', models.CharField(db_column='PREGUNTA_25', max_length=100)),
                ('pregunta_26', models.CharField(db_column='PREGUNTA_26', max_length=100)),
                ('pregunta_27', models.CharField(db_column='PREGUNTA_27', max_length=100)),
                ('pregunta_28', models.CharField(db_column='PREGUNTA_28', max_length=100)),
                ('pregunta_29', models.CharField(db_column='PREGUNTA_29', max_length=100)),
                ('pregunta_30', models.CharField(db_column='PREGUNTA_30', max_length=100)),
                ('pregunta_31', models.CharField(db_column='PREGUNTA_31', max_length=100)),
                ('pregunta_32', models.CharField(db_column='PREGUNTA_32', max_length=100)),
                ('pregunta_33', models.CharField(db_column='PREGUNTA_33', max_length=100)),
                ('pregunta_34', models.CharField(db_column='PREGUNTA_34', max_length=100)),
                ('pregunta_35', models.CharField(db_column='PREGUNTA_35', max_length=100)),
                ('pregunta_36', models.CharField(db_column='PREGUNTA_36', max_length=100)),
                ('pregunta_37', models.CharField(db_column='PREGUNTA_37', max_length=100)),
                ('pregunta_38', models.CharField(db_column='PREGUNTA_38', max_length=100)),
            ],
            options={
                'db_table': 'CUESTIONARIO_TRANSVERSAL',
                'managed': False,
            },
        ),
    ]
