CREATE DATABASE ENCUESTAS_DESS;
USE ENCUESTAS_DESS;

CREATE TABLE NIVEL_ACADEMICO(
ID_NA INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NIVEL VARCHAR(200));

CREATE TABLE UNIDAD_ACADEMICA(
ID_UA INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(500),
SIGLAS VARCHAR(200),
ID_NA INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_NA) REFERENCES NIVEL_ACADEMICO(ID_NA));

CREATE TABLE PROGRAMA_ACADEMICO(
ID_PA INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(600),
ID_UA INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_UA) REFERENCES UNIDAD_ACADEMICA(ID_UA));

CREATE TABLE EDAD(
ID_EDAD INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RANGO VARCHAR(200) NOT NULL);

CREATE TABLE PAIS(
ID_PAIS INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
PAIS VARCHAR(200) NOT NULL);

CREATE TABLE USUARIO(
ID_USUARIO INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO1 VARCHAR(50) NOT NULL,
APELLIDO2 VARCHAR(50) NOT NULL,
CURP VARCHAR(50) NOT NULL,
GENERO VARCHAR(30),
ESTADO_CIVIL VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONO VARCHAR(50) NOT NULL,
CODIGO_POSTAL VARCHAR(10),
CIUDAD VARCHAR(200),
ALCALDIA_MUNICIPIO VARCHAR(200),
BOLETA VARCHAR(50) NOT NULL,
ID_NA INTEGER UNSIGNED NOT NULL,
ID_UA INTEGER UNSIGNED NOT NULL, 
ID_PA INTEGER UNSIGNED NOT NULL,
ID_EDAD INTEGER UNSIGNED NOT NULL,
ID_PAIS_NACIMIENTO INTEGER UNSIGNED NOT NULL,
ID_PAIS_RESIDENCIA INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_NA) REFERENCES NIVEL_ACADEMICO(ID_NA),
FOREIGN KEY (ID_UA) REFERENCES UNIDAD_ACADEMICA(ID_UA),
FOREIGN KEY (ID_PA) REFERENCES PROGRAMA_ACADEMICO(ID_PA),
FOREIGN KEY (ID_EDAD) REFERENCES EDAD(ID_EDAD),
FOREIGN KEY (ID_PAIS_NACIMIENTO) REFERENCES PAIS(ID_PAIS),
FOREIGN KEY (ID_PAIS_RESIDENCIA) REFERENCES PAIS(ID_PAIS));

CREATE TABLE CUESTIONARIO(
ID_CUESTIONARIO INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(200) NOT NULL,
DESCRIPCION VARCHAR(500) NOT NULL,
IMAGEN VARCHAR(200) NOT NULL,
ID_NA INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_NA) REFERENCES NIVEL_ACADEMICO(ID_NA));

CREATE TABLE CIUDAD(
ID_CIUDAD INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CIUDAD VARCHAR(200));

CREATE TABLE ALCALDIA_MUNICIPIO(
ID_ALC_MUN INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ALCALDIA_MUNICIPIO VARCHAR(200),
ID_CIUDAD INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD));


CREATE TABLE CUESTIONARIO_TRANSVERSAL(
ID_CUESTIONARIO_TRANSVERSAL INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO INTEGER UNSIGNED NOT NULL,
PREGUNTA_1 VARCHAR(200) NOT NULL,
PREGUNTA_2 VARCHAR(200),
PREGUNTA_3 VARCHAR(200) NOT NULL,
PREGUNTA_4 VARCHAR(200) NOT NULL,
PREGUNTA_5 VARCHAR(200),
PREGUNTA_6 VARCHAR(200) NOT NULL,
PREGUNTA_7 VARCHAR(200) NOT NULL,
PREGUNTA_8 VARCHAR(200) NOT NULL,
PREGUNTA_9 VARCHAR(200) NOT NULL,
PREGUNTA_10 VARCHAR(200),
PREGUNTA_11 VARCHAR(200),
PREGUNTA_12 VARCHAR(200),
PREGUNTA_13 VARCHAR(200) NOT NULL,
PREGUNTA_14 VARCHAR(200) NOT NULL,
PREGUNTA_15 VARCHAR(200) NOT NULL,
PREGUNTA_16 VARCHAR(200) NOT NULL,
PREGUNTA_17 VARCHAR(200),
PREGUNTA_18 VARCHAR(200),
PREGUNTA_19 VARCHAR(200) NOT NULL,
PREGUNTA_20 VARCHAR(200) NOT NULL,
PREGUNTA_21 VARCHAR(200) NOT NULL,
PREGUNTA_22 VARCHAR(200),
PREGUNTA_23 VARCHAR(200),
PREGUNTA_24 VARCHAR(200),
PREGUNTA_25 VARCHAR(100) NOT NULL,
PREGUNTA_26 VARCHAR(100) NOT NULL,
PREGUNTA_27 VARCHAR(100) NOT NULL,
PREGUNTA_28 VARCHAR(100) NOT NULL,
PREGUNTA_29 VARCHAR(100) NOT NULL,
PREGUNTA_30 VARCHAR(100) NOT NULL,
PREGUNTA_31 VARCHAR(100) NOT NULL,
PREGUNTA_32 VARCHAR(100) NOT NULL,
PREGUNTA_33 VARCHAR(100) NOT NULL,
PREGUNTA_34 VARCHAR(100) NOT NULL,
PREGUNTA_35 VARCHAR(100) NOT NULL,
PREGUNTA_36 VARCHAR(100) NOT NULL,
PREGUNTA_37 VARCHAR(100) NOT NULL,
PREGUNTA_38 VARCHAR(100) NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE);






