INSERT INTO NIVEL_ACADEMICO(NIVEL)
VALUES
('Nivel Medio Superior'),
('Nivel Superior'),
('Posgrado');

INSERT INTO UNIDAD_ACADEMICA(NOMBRE, SIGLAS, ID_NA)
VALUES
('Escuela Superior de Ingeniería Mecánica y Eléctrica (ESIME), Unidad Zacatenco', 'ESIME ZACATENCO', 2),
('Escuela Superior de Ingeniería Mecánica y Eléctrica (ESIME), Unidad Culhuacán', 'ESIME CULHUACAN', 2),
('Escuela Superior de Ingeniería Mecánica y Eléctrica (ESIME), Unidad Azcapotzalco', 'ESIME AZCAPOTZALCO', 2),
('Escuela Superior de Ingeniería Mecánica y Eléctrica (ESIME), Unidad Ticomán', 'ESIME TICOMÁN', 2),
('Escuela Superior de Ingeniería y Arquitectura (ESIA), Unidad Zacatenco', 'ESIA ZACATENCO', 2),
('Escuela Superior de Ingeniería y Arquitectura (ESIA), Unidad Tecamachalco', 'ESIA TECAMACHALCO', 2),
('Escuela Superior de Ingeniería y Arquitectura (ESIA), Unidad Ticomán', 'ESIA TICOMÁN', 2),
('Escuela Superior de Ingeniería Textil (ESIT)', 'ESIT', 2),
('Escuela Superior de Ingeniería Química e Industrias Extractivas (ESIQIE)', 'ESIQIE', 2),
('Escuela Superior de Física y Matemáticas (ESFM)', 'ESFM', 2),
('Escuela Superior de Cómputo (ESCOM)', 'ESCOM', 2),
('Escuela Nacional de Ciencias Biológicas (ENCB)', 'ENCB', 2),
('Escuela Superior de Medicina (ESM)', 'ESM', 2),
('Escuela Nacional de Medicina y Homeopatía (ENMyH)', 'ENMH', 2),
('Escuela Superior de Enfermería y Obstetricia (ESEO)', 'ESEO', 2),
('Centro Interdisciplinario de Ciencias de la Salud, Unidad Milpa Alta (CICS-UMA)', 'CICS UMA', 2),
('Centro Interdisciplinario de Ciencias de la Salud, Unidad Santo Tomás (CICS-UST)', 'CICS UST', 2),
('Escuela Superior de Comercio y Administración, Unidad Santo Tomás (ESCA - Santo Tomás)', 'ESCA UST', 2),
('Escuela Superior de Comercio y Administración, Unidad Tepepan (ESCA - Tepepan)', 'ESCA TEPEPAN', 2),
('Escuela Superior de Economía (ESE)', 'ESE', 2),
('Escuela Superior de Turismo (EST)', 'EST', 2),
('Unidad Profesional Interdisciplinaria de Biotecnología (UPIBI)', 'UPIBI', 2),
('Unidad Profesional Interdisciplinaria en Ingeniería y Tecnologías Avanzadas (UPIITA)', 'UPIITA', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería, Campus Guanajuato (UPIIG)', 'UPIIG', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería, Campus Hidalgo (UPIIH)', 'UPIIH', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería, Campus Zacatecas (UPIIZ)', 'UPIIZ', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería y Ciencias Sociales y Administrativas (UPIICSA)', 'UPIICSA', 2),
('Unidad Profesional Interdisciplinaria de Energía y Movilidad (UPIEM)', 'UPIEM', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería Campus Coahuila (UPIIC)', 'UPIIC', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería, Campus Palenque (UPIIP)', 'UPIIP', 2),
('Unidad Profesional Interdisciplinaria de Ingeniería, Campus Tlaxcala (UPIIT)', 'UPIIT', 2);

INSERT INTO PROGRAMA_ACADEMICO(NOMBRE, ID_UA)
VALUES
('Ingeniería Eléctrica', 1),
('Ingeniería en Comunicaciones y Electrónica',1),
('Ingeniería en Control y Automatización',1),
('Ingeniería en Negocios Energéticos Sustentables',1),
('Ingeniería en Sistemas Automotrices',1),
('Ingeniería en Sistemas Energéticos y Redes Inteligentes',1),
('Ingeniería Fotónica',1),
('Ingeniería en Computación', 2),
('Ingeniería en Comunicaciones y Electrónica', 2),
('Ingeniería en Sistemas Automotrices', 2),
('Ingeniería Mecánica', 2),
('Ingeniería en Robótica Industrial',3),
('Ingeniería en Sistemas Automotrices',3),
('Ingeniería Mecánica',3),
('Ingeniería Aeronáutica', 4),
('Ingeniería en Sistemas Automotrices', 4),
('Ingeniería Civil', 5),
('Ingeniero Arquitecto', 6),
('Ingeniería Geofísica', 7),
('Ingeniería Geológica', 7),
('Ingeniería Petrolera', 7),
('Ingeniería Topográfica y Fotogramétrica', 7),
('Ingeniería Textil', 8),
('Ingeniería en Metalurgia y Materiales', 9),
('Ingeniería Química Industrial', 9),
('Ingeniería Química Petrolera', 9),
('Ingeniería Matemática', 10),
('Licenciatura en Física y Matemáticas', 10),
('Licenciatura en Matemática Algorítmica', 10),
('Ingeniería en Inteligencia Artificial', 11),
('Ingeniería en Sistemas Automotrices', 11),
('Ingeniería en Sistemas Computacionales', 11),
('Ingeniería en Sistemas Computacionales Móviles', 11),
('Licenciatura en Ciencia de Datos', 11),
('Ingeniería Bioquímica', 12),
('Ingeniería en Sistemas Ambientales', 12),
('Licenciatura en Biología', 12),
('Químico Bacteriólogo Parasitólogo', 12),
('Químico Farmacéutico Industrial', 12),
('Médico Cirujano Partero', 13),
('Médico Cirujano Homeópata', 14),
('Médico Cirujano Partero', 14),
('Licenciatura en Enfermería', 15),
('Licenciatura en Enfermería y Obstetricia', 15),
('Licenciado en Nutrición', 16),
('Licenciado en Optometría', 16),
('Licenciatura en Enfermería', 16),
('Licenciatura en Odontología', 16),
('Licenciatura en Trabajo Social', 16),
(' Médico Cirujano Partero', 16),
('Licenciado en Optometría', 17),
('Licenciatura en Psicología', 17),
('Licenciatura en Odontología', 17),
('Contador Público', 18),
('Licenciatura en Administración y Desarrollo Empresarial', 18),
('Licenciatura en Comercio Internacional', 18),
('Licenciatura en Negocios Digitales', 18),
('Licenciatura en Negocios Internacionales', 18),
('Licenciatura en Relaciones Comerciales', 18),
('Licenciatura en Mercadologia Digital', 18),
('Contador Público', 19),
('Licenciatura en Negocios Internacionales', 19),
('Licenciatura en Relaciones Comerciales', 19),
('Licenciatura en Contaduria y Finanzas Publicas', 19),
('Licenciatura en Economía', 20),
('Licenciatura en Turismo', 21),
('Ingeniería Ambiental', 22),
('Ingeniería Biomédica', 22),
('Ingeniería Biotecnológica', 22),
('Ingeniería en Alimentos', 22),
('Ingeniería Farmacéutica', 22),
('Ingeniería Biónica', 23),
('Ingeniería Mecatrónica', 23),
('Ingenieria en Sistemas Automotrices', 23),
('Ingeniería Telemática', 23),
('Ingeneria en Energia', 23),
('Ingeniería Aeronáutica', 24),
('Ingeniería Biotecnológica', 24),
('Ingeniería en Sistemas Automotrices', 24),
('Ingeniería Farmacéutica', 24),
('Ingeniería Industrial', 24),
('Ingeniería en Sistemas Automotrices', 25),
('Ingeniería Mecatrónica', 25),
('Ingeniería Ambiental', 26),
('Ingeniería en Alimentos', 26),
('Ingeniería en Sistemas Computacionales', 26),
('Ingeniería Mecatrónica', 26),
('Ingeniería Metalúrgica', 26),
('Ingeniería en Informática', 27),
('Ingeniería en Transporte', 27),
('Ingeniería industrial', 27),
('Licenciatura en Ciencias de la Informática', 27),
('Licenciatura en Administración Industrial', 27),
('Ingenieria Ferroviaria', 27),
('Licenciatura en Ciencias de la Informatica', 27),
('Ingeniería en Energía', 28),
('Ingeniería en Movilidad Urbana', 28),
('Ingeniería en Negocios Energéticos Sustentables', 28),
('Ingeniería en Sistemas Energéticos y Redes Inteligentes', 28),
('Ingeniería en Control y Automatización', 29),
('Ingeniería en Inteligencia Artificial', 29),
('Licenciatura en Ciencia de Datos', 29),
('Ingeniería Biotecnológica', 30),
('Ingeniería Civil', 30),
('Ingeniería Ferroviaria', 30),
('Licenciatura en Turismo Sustentable', 30),
('Ingeniería Biotecnológica', 31),
('Ingeniería en Inteligencia Artificial', 31),
('Ingeniería en Sistemas Automotrices', 31),
('Ingeniería en Transporte', 31),
('Licenciatura en Ciencia de Datos', 31);

INSERT INTO EDAD(RANGO)
VALUES
('24 años o menos'),
('25 años a 27 años'),
('28 años a 30 años'),
('Mayor de 31 años');

INSERT INTO PAIS(PAIS)
VALUES
('Afganistán'),
('Albania'),
('Alemania'),
('Andorra'),
('Angola'),
('Antigua y Barbuda'),
('Arabia Saudita'),
('Argelia'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bahrein'),
('Bangladesh'),
('Barbados'),
('Bélgica'),
('Belice'),
('Benín'),
('Bielorrusia'),
('Birmania / Myanmar'),
('Bolivia'),
('Bosnia y Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Bután'),
('Cabo Verde'),
('Camboya'),
('Camerún'),
('Canadá'),
('Catar'),
('Chad'),
('Chile'),
('China'),
('Chipre'),
('Ciudad del Vaticano'),
('Colombia'),
('Comoras'),
('Corea del Norte'),
('Corea del Sur'),
('Costa de Marfil'),
('Costa Rica'),
('Croacia'),
('Cuba'),
('Dinamarca'),
('Dominica'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Emiratos Árabes Unidos'),
('Eritrea'),
('Eslovaquia'),
('Eslovenia'),
('España'),
('Estados Unidos'),
('Estonia'),
('Eswatini'),
('Etiopía'),
('Filipinas'),
('Finlandia'),
('Fiyi'),
('Francia'),
('Gabón'),
('Gambia'),
('Georgia'),
('Ghana'),
('Granada'),
('Grecia'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guinea Ecuatorial'),
('Guyana'),
('Haití'),
('Honduras'),
('Hungría'),
('India'),
('Indonesia'),
('Irak'),
('Irán'),
('Irlanda'),
('Islandia'),
('Islas Marshall'),
('Islas Salomón'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jordania'),
('Kazajistán'),
('Kenia'),
('Kirguistán'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Lesoto'),
('Letonia'),
('Líbano'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo'),
('Macedonia del Norte'),
('Madagascar'),
('Malasia'),
('Malaui'),
('Maldivas'),
('Malí'),
('Malta'),
('Marruecos'),
('Mauricio'),
('Mauritania'),
('México'),
('Micronesia'),
('Moldavia'),
('Mónaco'),
('Mongolia'),
('Montenegro'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Níger'),
('Nigeria'),
('Noruega'),
('Nueva Zelanda'),
('Omán'),
('Países Bajos'),
('Pakistán'),
('Palaos'),
('Panamá'),
('Papúa Nueva Guinea'),
('Paraguay'),
('Perú'),
('Polonia'),
('Portugal'),
('Reino Unido'),
('República Centroafricana'),
('República Checa'),
('República del Congo'),
('República Democrática del Congo'),
('República Dominicana'),
('República Sudafricana'),
('Ruanda'),
('Rumania'),
('Rusia'),
('Samoa'),
('San Cristóbal y Nieves'),
('San Marino'),
('San Vicente y las Granadinas'),
('Santa Lucía'),
('Santo Tomé y Príncipe'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leona'),
('Singapur'),
('Siria'),
('Somalia'),
('Sri Lanka'),
('Sudán'),
('Sudán del Sur'),
('Suecia'),
('Suiza'),
('Surinam'),
('Tailandia'),
('Tanzania'),
('Tayikistán'),
('Timor Oriental'),
('Togo'),
('Tonga'),
('Trinidad y Tobago'),
('Túnez'),
('Turkmenistán'),
('Turquía'),
('Tuvalu'),
('Ucrania'),
('Uganda'),
('Uruguay'),
('Uzbekistán'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Yibuti'),
('Zambia'),
('Zimbabue');

INSERT INTO CUESTIONARIO(NOMBRE, DESCRIPCION, IMAGEN, ID_NA)
VALUES
('Cuestionario 1 nivel medio superior', 'Cuestionario prueba de nivel medio superior', 'Encuesta_Transversal.png', 1),
('Cuestionario 2 nivel medio superior', 'Cuestionario prueba de nivel medio superior', 'Encuesta_Transversal.png', 1),
('Cuestionario 3 nivel medio superior', 'Cuestionario prueba de nivel medio superior', 'Encuesta_Transversal.png', 1),
('Cuestionario 1 nivel superior', 'Cuestionario prueba de nivel superior', 'Encuesta_Transversal.png', 2),
('Cuestionario 2 nivel superior', 'Cuestionario prueba de nivel superior', 'Trayectoria_Escolar_MS.png', 2),
('Cuestionario 3 nivel superior', 'Cuestionario prueba de nivel superior', 'Trayectoria_Escolar_S.png', 2);


INSERT INTO CIUDAD(CIUDAD) VALUES
('Aguascalientes'),
('Baja California'),
('Baja California Sur'),
('Campeche'),
('Chiapas'),
('Chihuahua'),
('Ciudad de México (CDMX)')
('Coahuila'),
('Colima'),
('Durango'),
('Guanajuato'),
('Guerrero'),
('Hidalgo'),
('Jalisco'),
('Estado de México'),
('Michoacán'),
('Morelos'),
('Nayarit'),
('Nuevo León'),
('Oaxaca'),
('Puebla'),
('Querétaro'),
('Quintana Roo'),
('San Luis Potosí'),
('Sinaloa'),
('Sonora'),
('Tabasco'),
('Tamaulipas'),
('Tlaxcala'),
('Veracruz'),
('Yucatán'),
('Zacatecas');





