USE ENCUESTAS_DESS;

INSERT INTO CUESTIONARIO(NOMBRE, DESCRIPCION)
VALUES('CUESTIONARIO PARA EL ESTUDIO TRANSVERSAL MODALIDAD ESCOLARIZADA EGRESADOS EN 2020', 'Esta encuesta tiene como objetivo conocer tu trayectoria laboral y profesional, información que nos permitirá medir el impacto en el medio productivo como egresado politécnico, a los dos años de tu egreso.');

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Actualmente te encuentras laborando?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Sí', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No', 1);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuál es la razón principal por la que no te encuentras laborando?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('El mercado laboral está saturado', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Remuneración por debajo de mis expectativas', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Por cuestiones personales', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Falta de oferta laboral en mi área de estudio', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No estar titulado (a)/ falta de cedula profesional', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Cuestiones de salud', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No necesito trabaja', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Alta de experiencia en el perfil de puesto', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Por continuar estudiando', 2);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro', 2);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿En qué porcentaje coincide tu trabajo con tus estudios de licenciatura?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('0%', 3);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('25%', 3);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('50%', 3);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('75%', 3);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('100%', 3);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Ha sido o fue tu único empleo?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Sí', 4);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No', 4);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Señala el número de veces que has cambiado de trabajo, después del primer empleo que conseguiste al egresar:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('1', 5);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('2', 5);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('3', 5);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('4', 5);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('5 o más', 5);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('En cuanto a tu desarrollo profesional, al comparar tu puesto actual con el primero, consideras que:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mejoró', 6);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Empeoró', 6);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Permaneció igual', 6);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('En cuanto a tu nivel económico actual con respecto al primer empleo, consideras que:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mejoró', 7);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Empeoró', 7);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Permaneció igual', 7);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuánto tiempo te llevó conseguir tu empleo o tu primer empleo?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Empleado antes de egresar', 8);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Menos de 6 meses de egresar', 8);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De 6 meses a 1 año de egreso', 8);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Más de 1 año de egreso', 8);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Principal dificultad para encontrar empleo o el primer empleo?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Falta de vacantes en mi área de estudio', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Salario bajo/nulas o bajas prestaciones', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Horario', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No tenía experiencia', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No conozco quien me recomiende', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Tener cédula', 9);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ninguna', 9);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuál fue el principal requisito para conseguir tu empleo?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ser titulado', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Aprobar los exámenes de selección', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Dominio de otro idioma', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Manejo de tecnologías de la información y comunicación', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Experiencia', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Pasar una entrevista formal', 10);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro', 10);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Señala el principal medio a través del cual encontraste tu empleo actual:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Bolsa de trabajo institucional SISAE-SIBOLTRA', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Bolsa de trabajo de tu Unidad Académica', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Bolsa de trabajo externa', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Recomendación de compañeros de licenciatura', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Recomendación de un profesor', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Recomendación de un amigo o familiar', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Relaciones hechas en empleos anteriores', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Creación de un negocio, despacho, empresa propios', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Integración a un negocio familiar', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Servicio social', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Prácticas o estancias profesionales', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Agencia de colocación (head – hunters y outsourcing)', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Internet y/o app', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Por redes sociales', 11);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro', 11);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('El puesto que ocupas actualmente es:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Director general', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Dueño o socio de una empresa/ despacho/ rancho', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Profesional independiente', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Gerente/ Director de área', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Coordinador', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Subgerente / Subdirector de área', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Jefe de departamento', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ejecutivo de cuenta', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Jefe de oficina / sección / área', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Médico', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Empleado profesional', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Supervisor', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Analista especializado', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Vendedor en establecimiento', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Asistente', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ayudante', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Por cuenta propia no profesional', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Empleado no profesiona', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Auxiliar', 12);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro (especifique):', 12);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Nombre de la empresa:', 1);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Nombre del jefe inmediato:', 1);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('El tamaño de la empresa es:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Hasta 10 empleados (Micro)', 15);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Entre 11 y 50 empleados (Pequeña)', 15);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Entre 51 y 250 empleados (Mediana)', 15);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Más de 250 empleados (Grande)', 15);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('El régimen jurídico de la empresa/institución en que trabajas es:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Pública', 16);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Privada', 16);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Social', 16);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Actividad económica de la empresa:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Agrícola-ganadero/ silvícola/ etc.', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Industria extractiva', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Industria de la transformación', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Industria de la construcción', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Comercio', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Servicios bancarios/ financieros y seguros', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Transporte / comunicaciones', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Turismo', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Educación', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Servicios profesionales y técnicos', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Servicios de salud', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Servicios de gobierno', 17);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro (especifique):', 17);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Qué tipo de contratación tienes?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Contrato por obra o tiempo determinado.', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Base', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Confianza', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Honorarios', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Comisión', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Independiente', 18);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otro', 18);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuántas horas al día trabaja?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Menos de 5 horas', 19);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De 6 a 7 horas', 19);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Más de 8 horas', 19);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuál es su ingreso mensual neto?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Menos de $ 5,000.00', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De $ 5,001.00 a $ 9,000.00', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De $ 9,001.00 a $ 12,000.00', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De $ 12,001.00 a 15,000', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De $ 15,001 a $20,000.00', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De 20,001.00 a 25,000.00', 20);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Más de 25,001.00', 20);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Situación académica?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Titulado', 21);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No titutlado', 21);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Motivos por los cuales no te has titulado', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Estoy en proceso de titulación', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Me faltan requisitos (servicio social, idioma, prácticas profesionales, etc.)', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Costos de titulación', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('No he empezado/ni concluido la tesis', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Razones personales', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Por mi trabajo', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Falta de tiempo', 22);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Dificultad de trámites', 22);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Forma de titulación', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Proyecto de Investigación', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Tesis', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Memoria de experiencia profesional', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Examen de conocimiento por áreas', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Créditos de Posgrado', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Estudios de Licenciatura', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Seminario de titulación', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Escolaridad', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Curricular', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Práctica profesional', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Programa especial', 23);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Otra (especificar)', 23);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('¿Cuánto tiempo te llevó titularte?', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Menos de 12 meses', 24);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De 13 a 18 meses', 24);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('De 19 a 24 meses', 24);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Más de 24 meses', 24);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Expresar verbalmente opiniones o ideas en forma clara y precisa', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 25);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 25);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 25);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 25);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Expresar por escrito opiniones o ideas en forma clara y precisa', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 26);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 26);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 26);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 26);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Analizar ideas críticamente', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 27);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 27);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 27);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 27);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Aprender en forma independiente', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 28);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 28);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 28);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 28);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Actuar en el ámbito laboral conforme a una ética profesional', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 29);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 29);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 29);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 29);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Resolver problemas', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 30);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 30);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 30);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 30);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Actitud de liderazgo', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 31);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 31);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 31);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 31);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('A usar modelos y/o métodos matemáticos para analizar datos', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 32);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 32);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 32);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 32);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Formular argumentos lógicos', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 33);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 33);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 33);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 33);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Trabajar en colaboración con otras personas', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 34);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 34);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 34);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 34);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Formular ideas o pensamientos originales e innovadores', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Nada', 35);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Poco', 35);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Regular', 35);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mucho', 35);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Enseñanza teórica', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ampliar', 36);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mantenerr', 36);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Reducir', 36);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Enseñanza metodológica', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ampliar', 37);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mantenerr', 37);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Reducir', 37);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Prácticas: en empresa, laboratorio, campo, taller, clínica, etc.', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ampliar', 38);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Mantener', 38);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Reducir', 38);

INSERT INTO PREGUNTA(CUERPO, ID_CUESTIONARIO)
VALUES('Laboras en:', 1);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Ampliar', 39);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('México', 39);
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)
VALUES('Extranjero', 38);








