CREATE TABLE CUESTIONARIO_LONGITUDINAL(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_CUESTIONARIO INTEGER UNSIGNED NOT NULL,
ID_USUARIO INTEGER UNSIGNED NOT NULL,
PREGUNTA_1 INTEGER UNSIGNED NOT NULL,
PREGUNTA_2 INTEGER UNSIGNED NOT NULL,
PREGUNTA_3 INTEGER UNSIGNED NOT NULL,
PREGUNTA_4 INTEGER UNSIGNED NOT NULL,
PREGUNTA_5 INTEGER UNSIGNED NOT NULL,
PREGUNTA_6 INTEGER UNSIGNED NOT NULL,
PREGUNTA_7 INTEGER UNSIGNED NOT NULL,
PREGUNTA_8 VARCHAR(500) NOT NULL,
PREGUNTA_9 INTEGER UNSIGNED NOT NULL,
PREGUNTA_10 INTEGER UNSIGNED NOT NULL,
PREGUNTA_11 INTEGER UNSIGNED NOT NULL,
PREGUNTA_12 INTEGER UNSIGNED NOT NULL,
PREGUNTA_13 INTEGER UNSIGNED NOT NULL,
PREGUNTA_14 INTEGER UNSIGNED NOT NULL,
PREGUNTA_15 INTEGER UNSIGNED NOT NULL,
PREGUNTA_16 INTEGER UNSIGNED NOT NULL,
PREGUNTA_17 INTEGER UNSIGNED NOT NULL,
PREGUNTA_18 INTEGER UNSIGNED NOT NULL,
PREGUNTA_19 INTEGER UNSIGNED NOT NULL,
PREGUNTA_20 INTEGER UNSIGNED NOT NULL,
PREGUNTA_21 INTEGER UNSIGNED NOT NULL,
PREGUNTA_22 INTEGER UNSIGNED NOT NULL,
PREGUNTA_23 INTEGER UNSIGNED NOT NULL,
PREGUNTA_24 INTEGER UNSIGNED NOT NULL,
PREGUNTA_25 INTEGER UNSIGNED NOT NULL,
PREGUNTA_26 INTEGER UNSIGNED NOT NULL,
PREGUNTA_27 INTEGER UNSIGNED NOT NULL,
PREGUNTA_28 INTEGER UNSIGNED NOT NULL,
PREGUNTA_29 INTEGER UNSIGNED NOT NULL,
PREGUNTA_30 INTEGER UNSIGNED NOT NULL,
PREGUNTA_31 INTEGER UNSIGNED NOT NULL,
PREGUNTA_32 INTEGER UNSIGNED NOT NULL,
PREGUNTA_33 INTEGER UNSIGNED NOT NULL,
PREGUNTA_34 INTEGER UNSIGNED NOT NULL,
PREGUNTA_35 INTEGER UNSIGNED NOT NULL,
PREGUNTA_36 INTEGER UNSIGNED NOT NULL,
PREGUNTA_37 INTEGER UNSIGNED NOT NULL,
PREGUNTA_38 INTEGER UNSIGNED NOT NULL,
PREGUNTA_39 INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (ID_CUESTIONARIO) REFERENCES CUESTIONARIO(ID_CUESTIONARIO),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
FOREIGN KEY (PREGUNTA_1) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_1(ID),
FOREIGN KEY (PREGUNTA_2) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_2(ID),
FOREIGN KEY (PREGUNTA_3) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_3(ID),
FOREIGN KEY (PREGUNTA_4) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_4(ID),
FOREIGN KEY (PREGUNTA_5) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_5(ID),
FOREIGN KEY (PREGUNTA_6) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_6(ID),
FOREIGN KEY (PREGUNTA_7) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_7(ID),
FOREIGN KEY (PREGUNTA_9) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_9(ID),
FOREIGN KEY (PREGUNTA_10) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_10(ID),
FOREIGN KEY (PREGUNTA_11) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_11(ID),
FOREIGN KEY (PREGUNTA_12) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_12(ID),
FOREIGN KEY (PREGUNTA_13) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_13(ID),
FOREIGN KEY (PREGUNTA_14) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_14(ID),
FOREIGN KEY (PREGUNTA_15) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_15(ID),
FOREIGN KEY (PREGUNTA_16) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_16(ID),
FOREIGN KEY (PREGUNTA_17) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_17(ID),
FOREIGN KEY (PREGUNTA_18) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_18(ID),
FOREIGN KEY (PREGUNTA_19) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_19(ID),
FOREIGN KEY (PREGUNTA_20) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_20(ID),
FOREIGN KEY (PREGUNTA_21) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_21(ID),
FOREIGN KEY (PREGUNTA_22) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_22(ID),
FOREIGN KEY (PREGUNTA_23) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_23(ID),
FOREIGN KEY (PREGUNTA_24) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_24(ID),
FOREIGN KEY (PREGUNTA_25) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_25(ID),
FOREIGN KEY (PREGUNTA_26) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_26(ID),
FOREIGN KEY (PREGUNTA_27) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_27(ID),
FOREIGN KEY (PREGUNTA_28) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_28(ID),
FOREIGN KEY (PREGUNTA_29) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_29(ID),
FOREIGN KEY (PREGUNTA_30) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_30(ID),
FOREIGN KEY (PREGUNTA_31) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_31(ID),
FOREIGN KEY (PREGUNTA_32) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_32(ID),
FOREIGN KEY (PREGUNTA_33) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_33(ID),
FOREIGN KEY (PREGUNTA_34) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_34(ID),
FOREIGN KEY (PREGUNTA_35) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_35(ID),
FOREIGN KEY (PREGUNTA_36) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_36(ID),
FOREIGN KEY (PREGUNTA_37) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_37(ID),
FOREIGN KEY (PREGUNTA_38) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_38(ID),
FOREIGN KEY (PREGUNTA_39) REFERENCES CUESTIONARIO_LONGITUDINAL_PREGUNTA_39(ID));

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_1(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_1(RESPUESTA)
VALUES
('Sí'),
('No');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_2(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_2(RESPUESTA)
VALUES
('En proceso'),
('Falta acreditación de idioma'),
('Servicio Social'),
('Trámites administrativos lentos'),
('Falta de tiempo'),
('Falta de interés'),
('Razones personales'),
('Económicas'),
('Cuestiones de salud');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_3(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_3(RESPUESTA)
VALUES
('Maestría'),
('Doctorado'),
('Posdoctorado'),
('Curso de actualización'),
('Diplomado'),
('Especialidad'),
('Otra Licenciatura'),
('Capacitación para certificación'),
('Otro (¿cuál?)');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_4(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_4(RESPUESTA)
VALUES
('Sí'),
('No');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_5(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_5(RESPUESTA)
VALUES
('IPN'),
('UNAM'),
('UAM'),
('Tecnológico Nacional'),
('ITAM'),
('Tec. de Monterrey (ITESM)'),
('Otra ¿Cuál?');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_6(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_6(RESPUESTA)
VALUES
('Sí'),
('No');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_7(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_7(RESPUESTA)
VALUES
('Sí'),
('No');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_9(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_9(RESPUESTA)
VALUES
('Único Empleo'),
('De 2 a 4'),
('De 5 a 7 empleos'),
('Más de 7 empleos');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_10(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_10(RESPUESTA)
VALUES
('Mejor'),
('Igual'),
('Peor');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_11(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_11(RESPUESTA)
VALUES
('Económico'),
('Familiar'),
('Desarrollo Profesional'),
('Distancia'),
('Despido'),
('Ambiente laboral hostil, recorte de personal, cierre de empresa, salud, cuestiones personales'),
('Otro ¿Cuál?');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_12(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_12(RESPUESTA)
VALUES
('Presencial'),
('Home Office (virtual)'),
('Mixta');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_13(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_13(RESPUESTA)
VALUES
('Público'),
('Privado'),
('Social');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_14(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_14(RESPUESTA)
VALUES
('Micro (hasta 10 empleados)'),
('Pequeña (entre 11 y 50 empleados)'),
('Mediana (entre 51 y 250 empleados)'),
('Grande (más de 251 empleados)');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_15(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_15(RESPUESTA)
VALUES
('Agricultura, ganadería, silvicultura, caza y pesca'),
('Construcción'),
('Comercio'),
('Sistema judicial o legislativo'),
('Industria manufacturera'),
('Metalúrgica'),
('Energía'),
('Servicios de salud'),
('Servicios de educación y sociales'),
('Investigación y desarrollo'),
('Gobierno y organismos nacionales e internacionales'),
('Transportes'),
('Turismo'),
('Otro ¿Cuál?');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_16(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_16(RESPUESTA)
VALUES
('Dueño o socio de una empresa/CEO/ Emprendedor'),
('Director general'),
('Gerente / Director de área'),
('Subgerente / Subdirector de área'),
('Jefe de departamento o área'),
('Ejecutivo de cuenta'),
('Empleado técnico'),
('Vendedor'),
('Asistente técnico, ayudante o auxiliar, Call center'),
('Trabajo manual no calificado'),
('Docente'),
('Profesional independiente'),
('Otro ¿Cuál?');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_17(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_17(RESPUESTA)
VALUES
('Contrato por obra, proyecto o tiempo determinado'),
('Confianza'),
('Independiente'),
('Base'),
('Honorarios'),
('Comisión'),
('Otro ¿Cuál?');

CREATE TABLE CUESTIONARIO_LONGITUDINAL_PREGUNTA_18(
ID INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
RESPUESTA VARCHAR(500) NOT NULL);
INSERT INTO CUESTIONARIO_LONGITUDINAL_PREGUNTA_18(RESPUESTA)
VALUES
(''),































